docker pull mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
EXPOSE 80
docker pull mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /src
COPY ["IntroToMvc.csproj", "./"]
RUN dotnet restore "./PaymentGateway.csproj"
COPY . .
# WORKDIR "/src/."
RUN dotnet build "PaymentGateway.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "PaymentGateway.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PaymentGateway.dll"]